new dir to encapsulate upload command
OutlierVentures/arweave-bundler pull request #11
Opened 2023-11-13 22:14 UTC by Scott-Canning

Created `src/commands` directory to encapsulate commands outside of `cli.js` and moved the `upload` command

2023-11-14 10:26 UTC, aboutlo commented on src/cli.js
>    .option('private-key', {
Please try to move both the options in the `builder` function in the upload command.

2023-11-14 10:27 UTC, aboutlo commented on src/commands/upload.js
Let's rename it as `uploadCommand.js` given we already have the `upload.js` file with the actual implementation

2023-11-14 10:29 UTC, aboutlo requested changes
Looks good a couple of potential improvement before merging it

2023-11-14 14:39 UTC, Scott-Canning commented
Changed `commands/upload.js` to `commands/uploadCommand.js` and moved `upload` options into the associated `builder` function.

Test locally with `npx . upload build/ --private-key ${PRIVATE_KEY} --dry-run`

2023-11-14 15:01 UTC, aboutlo approved these changes
LGTM

2023-11-14 18:07 UTC, merged

2023-11-16 22:55 UTC, AronVanAmmers commented
:tada: This PR is included in version 0.1.4 :tada:

The release is available on:
- [GitHub release](https://github.com/OutlierVentures/arweave-bundler/releases/tag/v0.1.4)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@outlierventures/arweave-bundler/v/0.1.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: