Sc ar set
OutlierVentures/arweave-bundler pull request #20
Opened 2023-11-28 16:32 UTC by Scott-Canning

Implemented set using `arweave.js`

2023-11-30 11:05 UTC, aboutlo requested changes
A couple of changes and then we are good to go

2023-11-30 11:05 UTC, aboutlo commented on src/setRecord.js
> +        data: Math.random().toString().slice(-4)
Why `interaction` ?

A better name could be `postTransaction(data, contractAddress)`
but then we have to deal with arweave and the private key so we could use a closure and do currying.


we could do `createClient(arweave, privatekey, dryRun).setRecord(antAddress, manifestId)`

createClient can be extracted as function used between `setRecord` and `upload`


so an idea of the implementation could be:

import {setRecord, upload}

function createClient({arweave, privatekey, dryRun = false}) {
  return {
      setRecord(arweave, privateKey, dryRun) 
      upload(),
  }
}

... 

function setRecord ({arweave, privateKey, dryRun}) {
   return () => {
     // do your stuff here
    const tx  = buildTransaction(arweave,privateKey)  
     await arweave.transactions.sign(tx, privateKey);
     const response = await arweave.transactions.post(tx);
     return response
   }
}

Anyway, let's do this refactoring AFTER we merge this

2023-11-30 11:05 UTC, aboutlo commented on src/setRecord.test.js
> +        const { response, transactionId } = await setRecord('validAntAddress', 'validManifestId', privateKeyMock, false);
here you should check that the mocked methods have been called correctly by setRecord 

e.g. from upload.test.js
```
    assert.equal(getStatusMock.mock.callCount(), 2)
    assert.equal(getUploaderMock.mock.callCount(), 1)
    assert.deepEqual(getStatusMock.mock.calls[0].arguments, [txId])
    assert.deepEqual(getStatusMock.mock.calls[1].arguments, [txId])
```

2023-11-30 13:47 UTC, Scott-Canning commented on src/setRecord.js
> +        data: Math.random().toString().slice(-4)
the `writeInteraction` naming convention is consistent with the modern `warp-contracts` Arweave SmartWeave SDK used specifically for making SmartWeave contract interactions (SmartWeaveActions). See: https://academy.warp.cc/docs/sdk/basic/contract-methods. `postTransaction` may be too narrow in that the function encapsulates creating, signing, and posting SmartWeaveActions

2023-11-30 17:54 UTC, aboutlo approved these changes
LGTM

2023-11-30 17:55 UTC, merged

2023-12-01 14:12 UTC, AronVanAmmers commented
:tada: This PR is included in version 0.3.1 :tada:

The release is available on:
- [GitHub release](https://github.com/OutlierVentures/arweave-bundler/releases/tag/v0.3.1)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@outlierventures/arweave-bundler/v/0.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: